apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://backstage.github.io/charts
      chart: backstage
      targetRevision: 0.23.0
      helm:
        valueFiles:
          - $values/helm/values/dev/backstage-values.yaml
    - repoURL: git@github.com:JOELNATHAN544/om.git
      targetRevision: dep/deploy-backstage-developer-portal
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
