apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://backstage.github.io/charts
      chart: backstage
      targetRevision: 0.23.0
      helm:
        valueFiles:
          - $values/helm/values/prod/backstage-values.yaml
    - repoURL: https://github.com/JOELNATHAN544/om.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
