apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuers
  namespace: argocd
  labels:
    app.kubernetes.io/name: cert-issuers
    app.kubernetes.io/part-of: om-platform
    component: security
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform

  source:
    repoURL: __OM_GIT_REPO_URL__
    targetRevision: __OM_GIT_REVISION__
    path: security/cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
